export { default as Hero } from './hero'
export { default as Who } from './who'
export { default as History } from './history'
export { default as Team } from './team'
export { default as FAQ } from './faq'
